[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
force_grid_wrap = 0
include_trailing_comma = true

[tool.ruff]
ignore = ["D100", "D101", "D102", "D103"]
line-length = 88
target-version = "py310"
fix = true
select = [
    "E",  # Erros de estilo PEP8
    "F",  # Erros do Pyflakes
    "B",  # Erros do flake8-bugbear (boas práticas)
    "I",  # Organização de imports
]
ignore = [
    "E501", # Ignorar comprimento de linha (Black já cuida disso)
]

[tool.mypy]
python_version = "3.10"
strict = true
ignore_missing_imports = true
